---
# baseurl: /web.mcra  # for mcast.github.io/web.mcra/ but not http://mcra.t8o.org/
timezone: GB
highlighter: pygments
defaults:
  -
    scope:
      path: ""
    values:
      author: "Matthew Astley"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
