---
# baseurl: /web.mcra  # for mcast.github.io/web.mcra/ but not http://mcra.t8o.org/
timezone: GB
defaults:
  -
    scope:
      path: ""
    values:
      author: "Matthew Astley"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: "test"
      type: "pages"
    values:
      categories: "test"
gems:
  - jekyll-redirect-from

# thanks http://milanaryal.com/2015/writing-on-github-pages-and-jekyll-using-markdown/#for-kramdown-markdown
markdown: kramdown
kramdown:
  input: GFM

# from https://github.com/vmg/redcarpet#and-its-like-really-simple-to-use and wild examples
#markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "space_after_headers", "tables", "with_toc_data", "strikethrough", "superscript", "underline", "highlight", "footnotes", "hard_wrap" ]
